### ISSUE TITLE
Improve foil replacement

### ISSUE THREAD

**Issue by tooomm** [taw/magic-sealed-data#1]
As a reminder. :)
As seen in the dr4ft issue tracker on github.

<br>

from @taw:

>One minor thing I'm aware that I don't currently properly simulate is that initially, foils displaced another card of their rarity (except basic foils replaced common, as there were no basics). So you couldn't get 2nd rare or 4th uncommon as foil.
>
>Right now I have all foils replace commons like in current system.

**Comment by taw** [comment]
Is there any information on what were the foil rates back then, and if you could get multiple foils in one booster?

Even best information about modern foil rates were basically people's guesses on various reddit posts - at least we know there's now either:

* up to one foil, replacing common (in most sets)
* guaranteed foil in separate slot (in some sets)

**Comment by taw** [comment]
I have trouble finding out when the system changed.

[The Collation project](https://www.lethe.xyz/mtg/collation/index.html) says Invasion block used old system, Lorwyn block used new system, but nothing about blocks in between.

**Comment by taw** [comment]
[OK wiki says "prior to Time Spiral"](https://mtg.fandom.com/wiki/Foil_card#Slots)

**Comment by taw** [comment]
It's done now - for every expansion set from Urza's Legacy to Dissension.

Information about sets from that far ago is very sparse, I think that's all.
