### ISSUE TITLE
STX boosters have a Lesson slot

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#12]
Hi, 

This is the composition of Strixhaven draft boosters according to Wizards ([source](https://magic.wizards.com/en/articles/archive/feature/strixhaven-school-mages-product-overview-2021-03-25)):
> - 1 Rare or mythic rare
> - 1 Mystical Archive card (uncommon, rare, or mythic rare)
> - 1 Lesson card (common, rare, or mythic rare)
> - 3 Uncommons
> - 9 Commons
> - 1 Common card replaced by a foil card of any rarity* in 1 out of 3 boosters
>
> *This includes Mystical Archive cards

I have noticed you started implementing STX boosters, but I think you have not implemented a lesson slot which, apparently, exists in the booster alongside the Mythical Archive slot.

Hope this information is useful.

**Comment by taw** [comment]
I suspect more is going on, due to MDFCs and numbers being unusual with or without separating lessons.

Basically until https://www.lethe.xyz/mtg/collation/ writes their description, everything we have is preliminary. Every set is doing some gimmick or another these days.

By the way do you have any source for that? No idea what's the ratio of different lesson rarities.

**Comment by fverdoja** [comment]
the only source I had on this is the one I reported above. But I agree, there's most likely even more going on here.

**Comment by taw** [comment]
By the way I added pack data explorer to mtg.wtf: https://mtg.wtf/pack/stx

It should make it a lot clearer what's going on that by reading json

**Comment by fverdoja** [comment]
Oh wow that is a great visualization! Thanks :) I for one will definitely use it a lot.

**Comment by Senryoku** [comment]
Another oddity from the same source, uncommon lessons do not appear in the lesson slot, but in the standard uncommon slot instead. Confirmation here: https://twitter.com/mturian/status/1377389539073826817

**Comment by fverdoja** [comment]
but why?! 🤣

**Comment by taw** [comment]
Well, that solves the mystery of why there were only 75 uncommons not 80.

Common to Rare/Mythic Lesson rate is still a mystery.

**Comment by fverdoja** [comment]
I would assume the rate you defined of 9/10 times common lesson and 1/10 times a rare/mythic with rare appearing twice as likely seems reasonable to me... but of course, we can't really know until packs are opened.

**Comment by taw** [comment]
110 is one of typical sheet sizes, R:M is almost always 2:1, and this rate made the result match that sheet size at C:R rates within usual range. It's basically educated guess.

At least back in the days working backwards from sheet sizes was a pretty good way to figure out the rates; nowadays it's less reliable as their setups got more complex.

**Comment by fverdoja** [comment]
A bit on the side to the lesson discussion, but they announced the correct probabilities of the Mystical Archives rarities ([source](https://magic.wizards.com/en/articles/archive/magic-digital/mtg-arena-state-game-strixhaven-school-mages-2021-04-07)):
> this slot can be either uncommon (67%), rare (24.6%), or mythic rare (6.6%).

I am not sure if they were already known.

**Comment by taw** [comment]
Yeah, I found those Mystical Archives rates, already using them.

**Comment by taw** [comment]
So this is all done now?

**Comment by fverdoja** [comment]
I would say so, thanks
