### ISSUE TITLE
MH2 New-to-Modern slot

### ISSUE THREAD

**Issue by Senryoku** [taw/magic-sealed-data#13]
Modern Horizons 2 has a special "New-to-Modern" slot which is currently not implemented.
AFAIK it consists of cards #262 to #303 (https://scryfall.com/search?q=set%3Amh2+cn%3E%3D261+cn%3C%3D303&unique=cards&as=grid&order=set) and is completely independent of the rest of the pack (meaning you will get 2 rares/mythics or 4 uncommons).

WotC pack description:
> 1 Rare (including the five enemy fetch lands) or mythic rare
> 1 New-to-Modern reprint card (uncommon, rare, or mythic rare)
> 1 in 3 Boosters will contain a traditional foil card of any rarity
> 1 Token card/ad card

Sorry if it is already planned, but maybe there's some useful information here anyway :)

**Comment by taw** [comment]
Thanks.

I usually throw out some preliminary booster and fix it later, as these days every set has different boosters, and data is usually incomplete (like here - what's the ratio of rare to uncommon "new to modern" cards?).

And especially if anyone's interested in having set, theme, or collector boosters for anything, I can add this, but only if someone gives me really detailed information about this.

**Comment by taw** [comment]
Updated now.
