### ISSUE TITLE
MID has double-faced slots... kind of...

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#15]
Hello :)
I'm once again here reporting that Wizards is doing things in a new weird way for MID packs: there are two double face cards but they don't really have their own slot... kind of... 

According to [this page](https://magic.wizards.com/en/articles/archive/feature/boosters-and-products-innistrad-midnight-hunt-2021-09-02), draft boosters will have the following composition:
> * 1 Rare or mythic rare card
>    * Can be a double-faced or Booster Fun variant (showcase equinox, showcase eternal night, or borderless)
>* 3 Uncommon cards
>    * Can include up to one double-faced uncommon
>    * Can be showcase equinox uncommon cards
> * 1 Common double-faced card
>    * Can be a showcase equinox double-faced common card
> * 9 Common single-faced cards
>    * Can include showcase equinox common cards
> * 1 Eternal night basic land

![](https://media.wizards.com/2021/images/daily/en_d7Getwe63D.jpg)

From what I can understand (especially from the image), there seem to always be both a double-faced common plus one more double-face card among the three uncommons or the rare/mythic... which makes me think there are always two double faced cards, one of which always common...

They are really trying to make your life impossible it seems :)
I hope this information is useful, and thanks as usual for all the work you do!

**Comment by taw** [comment]
Thanks. As usual, I find it easier to just push out a first draft and then fix it later.

**Comment by taw** [comment]
DFC slots are fixed now.

(no support for showcase variants for any set except IKO yet, as they're quite complicated and very poorly documented; if that's something anyone cares about, please fill a ticket with all necessary information)

**Comment by fverdoja** [comment]
It looks very good now!
Thanks a lot for all your work as usual!
