### ISSUE TITLE
VOW collation information

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#16]
Hey,
I hope to be useful once again by providing information on the next set's draft booster collation.
According to WotC ([source](https://magic.wizards.com/en/articles/archive/feature/innistrad-crimson-vow-product-overview-2021-10-28)) this set will have the same booster structure than the last one (MID):

>1x Double- or single-faced rare or mythic rare
>1x Double- or single-faced uncommon
>1x Double-faced common
>2x Single-faced uncommons
>9x Single-faced commons
>1x Eternal night basic land

I think it's safe to assume the appearance rates of double-faced uncommon and rares are the same as the last set as well.

**Comment by taw** [comment]
Thanks.

**Comment by taw** [comment]
Done now, I made VOW work identically to MID.
