### ISSUE TITLE
Incorrect common/land slots for various small sets

### ISSUE THREAD

**Issue by awjackson** [taw/magic-sealed-data#18]
All small sets starting with Conflux should have 10 common slots and a basic land slot, not 11 common slots (Dragon's Maze and Fate Reforged have a special land slot instead). In the case of sets that don't have their own basic lands, the land slot contains a basic land from the "parent" large set (e.g. Conflux boosters contain a Shards of Alara basic).

Note that Gatecrash is a large set but it is affected by this issue--it doesn't have its own basic lands, so each booster contains a land from RTR instead.

In Oath of the Gatewatch, the card Wastes should not appear in the basic land slot. It is a regular common that appears in one of the 10 common slots. There are two full-art variations of Wastes that can appear in boosters (meaning Wastes is twice as common as each other individual common in the set) and two non-full-art variations that only appear in preconstructed decks. See https://www.lethe.xyz/mtg/collation/ogw.html

**Comment by awjackson** [comment]
List of affected sets:
Aether Revolt (needs +1 basic -1 common, basics from KLD)
Eldritch Moon (needs +1 basic -1 common, basics from SOI)
Oath of the Gatewatch (move Wastes from basic to common, basics from BFZ)
Journey Into Nyx (needs +1 basic -1 common, basics from THS)
Born of the Gods (needs +1 basic -1 common, basics from THS)
Gatecrash (needs +1 basic -1 common, basics from RTR)
Dark Ascension (needs +1 basic -1 common, basics from ISD)
Worldwake (needs +1 basic -1 common, basics from ZEN)
Alara Reborn (needs +1 basic -1 common, basics from ALA)
Conflux (needs +1 basic -1 common, basics from ALA)

**Comment by taw** [comment]
Can confirm from some pack opening videos that this is true.

Do you know if it affects foils? Can Conflux contain ALA basic foils etc.?

**Comment by taw** [comment]
Fixed now (assuming no different-set foil basics)

**Comment by awjackson** [comment]
It seems to vary between sets. BNG and JOU do not have THS basics on their foil common sheet, but OGW *does* has BFZ basics on its foil common sheet:

https://www.lethe.xyz/mtg/collation/bng.html
https://www.lethe.xyz/mtg/collation/jou.html
https://www.lethe.xyz/mtg/collation/ogw.html

Unfortunately, those three are the only sets with basics from a "parent" set for which Lethe has the foil common sheet layout.

Based on sheet math, my guess would be that sets with 60 commons (pre-OGW small sets) do not have parent set foil basics and sets with 70 or 101 commons (post-OGW small sets and Gatecrash) do.

**Comment by taw** [comment]
I think I'll just leave them without parent foil basics unless we have reliable information either way.

**Comment by awjackson** [comment]
Perhaps I should read the text and not just look at the pretty print sheet reconstructions. Here's what Lethe has to say about foils in most of the remaining "borrowed basic" sets:

Dark Ascension (https://www.lethe.xyz/mtg/collation/dka.html):
"Foils displace common cards. Note that foil basic lands do not appear."

Gatecrash (https://www.lethe.xyz/mtg/collation/gtc.html):
"The fifth variations of each basic land are probably on the foil uncommon sheet and so will displace B commons[...]Basic lands are the basic lands from Return to Ravnica with their original expansion symbols."

Eldritch Moon (https://www.lethe.xyz/mtg/collation/emn.html):
"The common foil sheet includes copies of the Shadows Over Innistrad basic lands."

Aether Revolt (https://www.lethe.xyz/mtg/collation/aer.html):
"All three basic land variations from Kaladesh can appear in packs (including as foils)."

Lethe does not have any information about Conflux, Alara Reborn or Worldwake, but it looks like my guess was correct: all 70-common (post-Origins) small sets and Gatecrash *do* have foil "borrowed basics" while all 60-common (pre-Origins) small sets presumably do not.

**Comment by taw** [comment]
So according to your knowledge, what's the final list of which sets with borrowed regular basics should and which shouldn't have borrowed basic foils?

**Comment by awjackson** [comment]
Aether Revolt: yes
Eldritch Moon: yes
Oath of the Gatewatch: yes
Journey Into Nyx: no
Born of the Gods: no
Gatecrash: yes
Dark Ascension: no
Worldwake: unknown, presumably no
Alara Reborn: unknown, presumably no
Conflux: unknown, presumably no

**Comment by taw** [comment]
Added AER, EMN, OGW borrowed foil basics. That should be all.
