### ISSUE TITLE
NEO collation information

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#19]
Hey,
I hope to be useful once again by providing information on the next set's draft booster collation.
According to WotC ([source](https://magic.wizards.com/en/articles/archive/feature/kamigawa-neon-dynasty-product-overview-2022-01-27)) this set will have the following booster structure:
![draft booster collation](https://media.wizards.com/2022/images/daily/en_uV6TSNyNy6.jpg)

**Comment by taw** [comment]
I added them, one unknown is DFC C/U rate, as no rate works exactly for both C and U rates.

I picked 30% U, as it makes SFC U and DFC U rates match exactly, but that makes DFC C have higher rate than SFC C.

1/3 U would be cleaner, and sort of split the difference (DFC U a bit underrepresented, DFC C a bit overrepresented).

**Comment by fverdoja** [comment]
Hi, just a small thing, the image above seems to hint that the common dual lands will appear in the land slot, not in the common slot. 
No good information on the rates is given, but my guess is that the 10 common dual lands will appear 1/3 of the times, 10 basic lands 1/3 of the times, and the ukiyo-e lands 1/3, which is easy and would respect the "ukiyo-e lands in 33% of packs" claim. 
Of course, another option is dual 1/2 of times, ukiyo-e lands 1/3 of times, and normal basics 1/6 of times, to respect the "half time basic, half time dual" drop rate, but I don't think this is the case because it would make normal basic lands rarer than the ukiyo-e lands.

**Comment by taw** [comment]
There's 10 duals, 10 normal basics, and 10 ukiyoe basics, so that's equal numbers on print sheet. Everything is 1/30, and the "ukiyo-e lands in 33% of packs" works perfectly, and we have zero reason to believe otherwise.

([Uncharted Haven](https://mtg.wtf/card/neo/281/Uncharted-Haven) is C).

I'll update the rate tomorrow.

**Comment by taw** [comment]
Updated now. It also makes SFC C (1/101 instead of 1/111) vs DFC C (7/60) rarity gap a bit smaller, but it's still there.

Not sure if we can really tell 3:7 U:C (exact U DFCs, too much C DFCs) vs 3:6 U:C (too high both DFCs) empirically.

**Comment by taw** [comment]
Closing this. Please reopen if any new information shows up, or there are any bugs.
