### ISSUE TITLE
A-B-U-REV

### ISSUE THREAD

**Issue by 7stringplayer** [taw/magic-sealed-data#2]
are these sets ever going to fix.  you get way to many basic lands when you try and draft them.  Almost making them undraftable

**Comment by taw** [comment]
Well, they are literally "almost undraftable". They were created before concept of "draft" even existed, and they're known to be terrible for drafitng. 

[You can check what their print sheets looked like](http://www.lethe.xyz/mtg/collation/lea.html).

As far as I know, data about ABUR fully matches "The Collation Project" and actual physical packs.

This is a case where drafting fake packs (with no basics on common sheet) would work a lot better than drafting accurate packs (with as many basics as you see).

I think you'd need to draft more packs to get a fun experience.

**Comment by taw** [comment]
Closing the issue, since there's no problem with data as far as I know.
