### ISSUE TITLE
Streets of New Capenna booster collation

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#20]
Here's the collation information for SNC draft packs.

Thanks as usual for all your efforts.

> Streets of New Capenna Draft Boosters contain:
> * 1 Rare or mythic rare card
> * 3 Uncommons
> * 10 Commons (In 33% of Streets of New Capenna Draft Boosters, a traditional foil of any rarity replaces a common.)
> * 1 Basic land, featuring a metropolis basic land in 33% of Draft Boosters
> * 1 Token, ad, or counter punch-out card

([source](https://magic.wizards.com/en/articles/archive/feature/streets-of-new-capenna-product-overview-2022-04-07))

**Comment by taw** [comment]
[It's all there](https://mtg.wtf/pack/snc).

I guess basics ratio needs adjusting as I have them 2:2, and you're saying it should be 4:2.

Take a look to see if there are any other issues.

**Comment by fverdoja** [comment]
This was fast! :)

Aside for the basic ratio, it looks good to me.

**Comment by taw** [comment]
Basics fixed, so that should all be done now.
