### ISSUE TITLE
UNH not existent MTGJSON id

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#21]
I am not sure if I need to report this here or to MTGJSON, but I noticed one card in the boosters that has a not a valid MTGJSON id 
```
SET    BOOSTER    SHEET           ID
UNH    default    rareMythic      bf063f58-554c-51dc-8a84-ce41a5d19b02
UNH    default    unhingedFoil    bf063f58-554c-51dc-8a84-ce41a5d19b02
```

**Comment by taw** [comment]
100% of time it happens because mtgjson changes uuids. It usually gets cleared eventually as that update propagates.

**Comment by taw** [comment]
I can confirm this uuid existed previously in mtgjson UNH.

**Comment by taw** [comment]
That's from git history of my uuid mapping file at https://github.com/taw/magic-search-engine/blob/master/index/uuids.txt:  

```
-unh    35      bf063f58-554c-51dc-8a84-ce41a5d19b02    Johnny, Combo Player
+unh    35      f1d410f6-c040-5ed5-87a6-e059120c17e3    Johnny, Combo Player
```

**Comment by fverdoja** [comment]
thanks a lot for checking this so fast :) your work is always very appreciated.

**Comment by taw** [comment]
Is this fixed now?

**Comment by fverdoja** [comment]
Seems so, thank you!
