### ISSUE TITLE
Collector Number Mistakes in MID

### ISSUE THREAD

**Issue by Meerkov** [taw/magic-sealed-data#22]
```
"dfc_uncommon": {
        "total_weight": 23,
        "cards": {
          "mid:105a": 1,
          "mid:126a": 1,
          "mid:139a": 1,
          "mid:13a": 1,
          "mid:141a": 1,
          "mid:160a": 1,
          "mid:165a": 1,
          "mid:174a": 1,
          "mid:181a": 1,
          "mid:187a": 1,
          "mid:190a": 1,
          "mid:218a": 1,
          "mid:231a": 1,
          "mid:256a": 1,
          "mid:2a": 1,
          "mid:3a": 1,
          "mid:45a": 1,
          "mid:47a": 1,
          "mid:4a": 1,
          "mid:63a": 1,
          "mid:68a": 1,
          "mid:85a": 1,
          "mid:92a": 1
        }
      },
```
All of these are wrong. The collector number of `139a` should be either `139` or `292`, for example.
https://scryfall.com/card/mid/139/fangblade-brigand-fangblade-eviscerator
https://scryfall.com/card/mid/292/fangblade-brigand-fangblade-eviscerator

**Comment by taw** [comment]
We do not follow scryfall numbers.

Gatherer and mtg.wtf both use A for front side of DFC and B for back side of DFC.

* https://mtg.wtf/card/mid/105a
* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534877
