### ISSUE TITLE
Foil and second DFC slots should be mutually exclusive in SOI and EMN

### ISSUE THREAD

**Issue by awjackson** [taw/magic-sealed-data#23]
Shadows over Innistrad and Eldritch Moon boosters have a 1/8 chance to contain a rare or mythic rare DFC in place of a common, in addition to the usual chance of a foil replacing a common. According to Lethe (https://www.lethe.xyz/mtg/collation/soi.html https://www.lethe.xyz/mtg/collation/emn.html) these are mutually exclusive: "It is not possible to get a rare or mythic rare double-faced card and a foil in the same pack."

**Comment by taw** [comment]
Thanks, I'll take a look at it.

**Comment by taw** [comment]
Fixed.
