### ISSUE TITLE
DMU collation information

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#24]
Hey,
I hope to be useful once again by providing information on the next set's draft booster collation.
According to WotC ([source](https://magic.wizards.com/en/articles/archive/feature/dominaria-united-product-overview-2022-08-18)) this set will have the following booster structure:
![draft booster collation](https://media.wizards.com/2022/images/daily/en_2NNuwenyds.jpg)

**Comment by taw** [comment]
Thanks. I'll add it soon.

**Comment by taw** [comment]
Done the basic version. Still need to add legendary rule.

**Comment by taw** [comment]
All done now, with legend rule as stated on the picture.
