### ISSUE TITLE
BRO collation information

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#26]
Hey,
I hope to be useful once again by providing information on the next set's draft booster collation.
According to WotC ([source](https://magic.wizards.com/en/news/feature/whats-inside-the-brothers-war-boosters)) this set will have the following booster structure:
* 1 Rare or mythic rare, that can potentially be in the borderless frame
* In a third of boosters replacing a common, 1 traditional foil card that can be a basic land, common, uncommon, rare, or mythic rare, or a retro artifact or retro schematic card
* 1 Retro artifact or retro schematic card
* 1 Basic land or mech land card
* 3 Non-foil uncommons
* 10 Non-foil commons, unless one is replaced by a traditional foil card of any rarity

![booster](https://media.wizards.com/2022/images/daily/en_4UiFYywxcR.jpg)

**Comment by taw** [comment]
Looks easy enough this time.

Does Arena have retro artifacts and schematics? Is it just like normal booster without foils and without basic slot?

**Comment by fverdoja** [comment]
Yeah I am pretty sure Arena has retro as well. My guess is that on Arena schematics are actually card styles you can buy in the shop

**Comment by taw** [comment]
Packs are ready:

* https://mtg.wtf/pack/bro
* https://mtg.wtf/pack/bro-arena

Foil rates are estimated, just counting every card in BRR+BRO by its rarity symbol (excluding BRO cards over base size). If anyone has better idea, I can tweak that, but this is low priority.

**Comment by fverdoja** [comment]
Looks good, given the information we have

**Comment by taw** [comment]
OK, closing the issue. If there are any problems, or we discover new information (from Collation Project or such), feel free to reopen.

**Comment by fverdoja** [comment]
I went to Prerelease yesterday, and I noticed packs actually have no basic lands slots, they have 10 commons and sometimes the 10th common is replaced by a full art mech land. I believe the image above is actually describing it correctly (25% rate of a mech land), while the text version is wrong. I notice now for the first time the discrepancy. Interestingly it seems normal basic lands cannot be found in draft boosters.

Additional evidence in this video: https://www.youtube.com/watch?v=Ig870RdKTvQ

**Comment by taw** [comment]
So I'm guessing this means Arena is also getting this common/mech basic slot?

**Comment by fverdoja** [comment]
Looking at [this](https://www.youtube.com/watch?v=IIrVg7NGUaU) video from the steamer early access event, it seems no packs had basic lands, seems all arena packs are 1R 3U 10C 1old border

**Comment by taw** [comment]
OK, updated:

* https://mtg.wtf/pack/bro
* https://mtg.wtf/pack/bro-arena

Does it look correct now?

**Comment by fverdoja** [comment]
I think it's always either foil or mech land, I have never seen it happens together, which is anecdotal, but also the picture above seems to indicate that, with the last slot being replaced in case of foils. Otherwise, everything else looks good to me.

**Comment by taw** [comment]
So 1/3 foil (4/12), 1/4 basic mech land (3/12), and the rest (5/12) with a common?

And on Arena I guess just a common in that slot?

**Comment by taw** [comment]
Foils and mech lands are now exclusive:

* https://mtg.wtf/pack/bro

I'll close the issue then. If you find any problems with this (or we discover any new information), feel free to reopen this one or create a new ticket.

**Comment by fverdoja** [comment]
> So 1/3 foil (4/12), 1/4 basic mech land (3/12), and the rest (5/12) with a common?
> 
> And on Arena I guess just a common in that slot?

Sounds correct to me. Thanks for your work.
