### ISSUE TITLE
number of boosters in booster boxes

### ISSUE THREAD

**Issue by kodawah** [taw/magic-sealed-data#28]
Is there a way to determine how many booster packs would be present in a booster box? Usually it's 36, but master sets and old boosters have a variable number.

If not, would it be possible to add this kind of information? Would it make sense to so here or in mtgjson?

**Comment by taw** [comment]
This information is per-product, not per-booster type. Boosters for the same set are often sold in multiple counts, 1, 36, and some others (like fat packs etc.).

I think you might want to discuss this here - https://github.com/mtgjson/mtgjson/issues/799 - they're trying to build some product information.

I'm sort of involved in this, as logic to matching which product corresponds to which precon or booster type will probably be on my side, but I'd prefer if they handled counts per box.

**Comment by kodawah** [comment]
ok let's move discussion there - before we close this, do you know of any reliable source this kind of data could be retrieved from?

**Comment by taw** [comment]
I never looked into this question. Wizards used to have product pages (they reorganize their website every few years killing old links, so only really available in web archive for old sets), there's MTG wiki, shops selling Magic can have such info etc. Possibly someone in the linked issue will know better.

**Comment by kodawah** [comment]
this is being implemented in https://github.com/mtgjson/mtgjson/pull/997
