### ISSUE TITLE
CMR is missing the etched sheet

### ISSUE THREAD

**Issue by kodawah** [taw/magic-sealed-data#29]
It looks like there is a very low probably to get an etched foil card in a normal draft booster

source: https://www.youtube.com/shorts/15r1WEULmC8
product page: https://wpn.wizards.com/en/news/whats-inside-each-commander-legends-product

in CMR it would be one of these commanders: https://scryfall.com/search?q=is%3Aetched+s%3ACMR&unique=cards&as=grid&order=name, luckily coming with a different collectors number

would it be possible to add a specialized sheet for this usecase?

**Comment by taw** [comment]
Oh it's not just CMR. The data is missing showcase cards for all sets [except for IKO](https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_showcase.rb). (for cases where it's purely visual and they replace non-showcase cards with some chance; cards that are actually different should be implemented)

I did it once with IKO, but it's a massive pain, as it's not documented anywhere, every set does it just slightly differently.

If someone was to gather all the data for it, I could handle the coding side. This could be done for all post-IKO standard sets.

IKO logic is - if card has showcase variant it's C2:C1, if it doesn't it's C3 etc.; same for other rarities. IIRC it wasn't the same logic for other sets, but I'm not totally sure.

**Comment by kodawah** [comment]
oh i guess etched cards count as showcase? i just thought etched were missing because normally they are found in set and collector booster, and i brought CMR up because it was the only one with those kind of cards found in normal drafts

**Comment by taw** [comment]
[Now that a whole new booster description system is supported](https://github.com/taw/magic-search-engine/issues/164), I think this might be relatively easy to do, as long as we have full information about it.

**Comment by taw** [comment]
It should be done now with https://github.com/taw/magic-search-engine/pull/190
