### ISSUE TITLE
Double master's booster format

### ISSUE THREAD

**Issue by TworkC** [taw/magic-sealed-data#3]
Commons:8
Uncommons:3
Rare/Mythic:2
Foils:2

Format for 2xm boosters

**Comment by taw** [comment]
Some information: https://mtg.gamepedia.com/Double_Masters

[The Collation Project](https://www.lethe.xyz/mtg/collation/) will likely have more details at some point.

Also for what it's worth, [2XM is supposed to have special draft rules](https://magic.wizards.com/en/articles/archive/making-magic/double-deal-2020-07-20):

> The third big change came about in Draft. It didn't take many playtests to recognize that it was unfun to open two amazing rares/mythic rares and have to pass one away, so the design team altered drafting with Double Masters to have you choose two cards on the first pick after opening a booster. While this might seem like a small thing, it has a big impact on the draft, not just because you can take both your rares/mythic rares, but also because it lets you take two synergistic cards which can often help steer how the rest of your draft goes.

Any such special rules are not currently saved anywhere.

**Comment by taw** [comment]
There's 2XM now, but it's likely not completely accurate. All sets nowadays have extra weird rules.

**Comment by taw** [comment]
Looking at https://www.lethe.xyz/mtg/collation/2xm.html I think it's all good.
