### ISSUE TITLE
30A is missing

### ISSUE THREAD

**Issue by Meerkov** [taw/magic-sealed-data#30]
Hey, can you add 30th Anniversary?

it has a slightly different pack distribution than ABU.

**Comment by taw** [comment]
Sure. Could you provide info about the packs on this ticket?

**Comment by Meerkov** [comment]
https://scryfall.com/sets/30a?as=grid&order=set This is a list of each card

> Each pack of 30th Anniversary Edition contains 15 cards, 13 cards in the modern frame—1 rare, 3 uncommons, 7 commons, and 2 basic lands—plus one basic land in the retro frame, one additional retro frame card, and a token.

https://mtg.fandom.com/wiki/30th_Anniversary_Edition

This is the original Beta set, with a few changes.
Six cards are removed
> Contract from below, dark pact, Demonic Attorney, Crusade, Earthbind, Weakness

The only card that doesn't match its original rarity is another special add-on for 30th Anniversary Edition: Sol Ring is a card that's near and dear to many players, so we created a special new crop of the original art that will appear at common rarity in both the modern and retro frames. Sol Ring also appears at uncommon.

Each dual land has 2x the normal frequency. This is true for both modern frame and retro frame dual lands.

> The retro frame slot is especially interesting, as approximately three out of every ten packs will contain a rare retro frame card—anything from a Black Lotus to a Mahamoti Djinn to a Volcanic Island. That means that some packs will contain two rares, and some will even contain two pieces of the Power 9!

**Comment by Meerkov** [comment]
https://magic.wizards.com/en/news/announcements/celebrate-30-years-magic-gathering-30th-anniversary-edition-2022-10-04

**Comment by taw** [comment]
So there are no foils there?

**Comment by taw** [comment]
For ~30% of retro cards being rare, duals being 2x rate of other rares, and C<U<R, the rates need to be something like (how many times each card would need to appear on sheet if they were on the same one):

* 4x Commons and Duals
* 3x Uncommons
* 2x Other Rares

So it's not totally flat, but close to it. This isn't the only solution as U rate is not fully determined by our rules, but it results in 29.7% rare rate, exact 2x dual rate, and good C<U<R separation.

Normally on special sheets C:U:R rates are closer to 4:2:1 or 5:2:1. not 4:3:2.

**Comment by taw** [comment]
It's done - https://mtg.wtf/pack/30a

Feel free to reopen this issue if something is missing.
