### ISSUE TITLE
Praetors in ONE boosters

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#31]
Hi,
ONE boosters contain the four additional preators that came in previous sets, namely:
> 1 Praetor card from among the following (Sheoldred, the Apogoalypse/Vorinclex, Monstrous Raider/Urabrask, Heretic Praetor/Jin-Gitaxis, Progress Tyrant) may replace the Rare slot of Phyrexia: All Will Be One limited booster packs, at a ratio of approximately 1:60.
([source](https://magic.wizards.com/en/mtgarena/drop-rates))

While the source regards primarily Arena packs, the same praetors have been confirmed to be present also in paper draft booster packs ([reddit thread](https://www.reddit.com/r/MagicArena/comments/10w7wmk/psa_praetors_from_previous_sets_are_splashed_into/), where you can see the answer by WotC staff in first comment) ([source](https://magic.wizards.com/en/news/feature/collecting-phyrexia-all-will-be-one) mentioned in the comments)
For paper boosters no precise drop rate is mentioned but the comments make me assume the rate is the same 1:60.
From what I read, I don't think those four praetors can appear in the foil slot in paper boosters. Of course, Elesh Norn can.

**Comment by taw** [comment]
So based on other examples, it means ~1/60 of packs will contain one of 4 extra cards.

There's 20 M and 60 R. 60:1 does not correspond to any nice multiple. It would make the Preators about 0.6x as frequent as mythics, which is a weird rate.

No idea what "Reprint Praetors do not appear in store packs." means. What are "store packs"?

**Comment by fverdoja** [comment]
I think it refers to packs that can be bought from the store on Arena, which are 8-card packs, differently from the 15-card limited packs used for drafts and sealed on Arena.

**Comment by taw** [comment]
Is it the most basic printing in each case? And none of the fancy printings?

**Comment by taw** [comment]
Does it look right now?

* https://mtg.wtf/pack/one
* https://mtg.wtf/pack/one-arena

**Comment by fverdoja** [comment]
It does look good to me. Thanks.

> Is it the most basic printing in each case? And none of the fancy printings?

On Arena, yeah. I honestly have no idea what printing you get in paper, but I imagine for now basic printing should be ok.

**Comment by taw** [comment]
OK, closing it then.

**Comment by fverdoja** [comment]
Thanks a lot. I don't think you committed it here though, maybe?
