### ISSUE TITLE
Shadows over Innistrad Remastered

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#33]
Hi,
Shadows over Innistrad Remastered has just been added to Arena, it has draft packs which are pretty standard except for a bonus sheet that actually rotates weekly: 1R/M 3U 10C 1Bonus.
Not sure what the best way to implement the bonus sheet is, but I imagine it is either putting all the cards together or having equally likely booster options, one per week, which ultimately result in the same probabilities. Unfortunately no information about the probabilities of the different rarities for the bonus sheet is given, but anecdotally I can tell you it is somehow proportional to the rarity of the cards.
No basic lands and no foils, as usual on Arena.

Set: https://magic.wizards.com/en/news/card-image-gallery/shadows-over-innistrad-remastered-card-image-gallery

Bonus sheet: https://magic.wizards.com/en/news/mtg-arena/shadows-of-the-past-card-list-and-schedule

**Comment by taw** [comment]
It's actually easy enough to do sir-arena-1 to sir-arena-4, with proper names.

What's blocking me is https://github.com/mtgjson/mtgjson/issues/1050

**Comment by fverdoja** [comment]
I see... out of curiosity, why do you need their melded forms in packs?

**Comment by taw** [comment]
I need the melded forms to import them into the card database. It doesn't really understand a situation where half of a card is present and the other half is not.

I could temporarily drop the meld cards, or manually enter the melded side, but I'm a bit busy for such hacks, so I'll wait for mtgjson to fix it, then I'll do the packs (in 4 versions).

**Comment by taw** [comment]
SIS print sheets are implemented.

https://mtg.wtf/card/sis/1/Angel-of-Flight-Alabaster is tagged rare (A) etc.

I can do SIR boosters just without meld cards.

**Comment by taw** [comment]
SIR boosters implemented, but without meld cards until that bug is fixed in mtgjson:

* https://mtg.wtf/pack/sir-arena-1
* https://mtg.wtf/pack/sir-arena-2
* https://mtg.wtf/pack/sir-arena-3
* https://mtg.wtf/pack/sir-arena-4

**Comment by fverdoja** [comment]
Looks good, the only thing I am not sure about if whether cards on the bonus sheet have same rate independent of rarity... I don't think wizards has reported on that, but for example in he artifact bonus sheet in bro rarity mattered, but it was also a larger sheet... so not sure...

**Comment by taw** [comment]
There were small sheets split by rarity in the past, like various small DFC sheets.

For Arena of course technical printing considerations don't exist.

If there's no information, for such sheets usually safe starting rate is 1x for M, 2x for R, 4x for U, and 8x for U, this is usually close enough to the true rate. For physical sheets it was possible to reverse engineer exact ratios from card counts, but I don't think this process even be meaningful for Arena.

If you think rarities are likely to matter, feel free to change [`sis.txt`](https://github.com/taw/magic-search-engine/blob/master/data/print_sheets_new/sis.txt) to have rarity based multiples (A1 for mythic from sheet A, B8 for common from sheet B etc.), and the system knows what to do with that already.

**Comment by taw** [comment]
Meld cards issue is now resolved as mtgjson fixed them.

**Comment by fverdoja** [comment]
For arena this is a good proxy: https://www.17lands.com/card_ratings
For each card there's a "seen" value that tells how many copies were opened by people playing limited with the 17lands client on their computer. For example we can see that:
* Bloodline Keeper (M): 641 copies seen

* Angel of Flight Alabaster (R): 2035
* Havengful Runebinder (R): 2855

* Avacyn's Collar (U): 14792
* Stromkirk Captain (U): 10281

* Elder Cathar (C): 41137
* Traveler's Amulet (C): 44551

So it's clear they don't appear at the same rate, I think it's ok to assume the 1 - 2 - 4 - 8 rate you were mentioning, the numbers are not perfectly matching that, but are not too far off either...

**Comment by taw** [comment]
https://www.17lands.com/card_ratings rates you linked seem to be a lot more skewed than 1-2-4-8. It looks more like 1-2-10-40.

Or is it a draft, and commons just pass through more hands, while rares/mythics get picked first or second?

**Comment by fverdoja** [comment]
(sorry I removed my previous comment because it was incomplete, here's that again with more complete information)
For arena this is a good proxy: https://www.17lands.com/card_ratings
For each card there's a "seen" value that tells how many copies were opened by people playing limited with the 17lands client on their computer. I am pretty sure that if a card is not picked in draft and someone else sees it the value of seen is counted twice. However, there's also an "ALSA" value that tells you when the card was seen last on average.

By looking at the data for SIR we can see that:

  |   | Seen | ALSA | Seen/ALSA | Rate
-- | -- | -- | -- | -- | --
M | Bloodline Keeper | 641 | 1,42 | 451,41 | 1,00
R | Mayor of Avabruck | 1672 | 1,76 | 950,00 | 2,10
R | Angel of Flight Alabaster | 2035 | 2,26 | 900,44 | 1,99
R | Kruin Outlaw | 2477 | 2,56 | 967,58 | 2,14
R | Havengful Runebinder | 2855 | 3,13 | 912,14 | 2,02
U | Drogskol Captain | 9795 | 4,08 | 2400,74 | 5,32
U | Stromkirk Captain | 10281 | 4,24 | 2424,76 | 5,37
U | Immerwolf | 11197 | 4,53 | 2471,74 | 5,48
U | Diregraf Captain | 11973 | 5,03 | 2380,32 | 5,27
U | Butcher's Cleaver | 13922 | 5,3 | 2626,79 | 5,82
U | Avacyn's Collar | 14792 | 5,6 | 2641,43 | 5,85
C | Elder Cathar | 41137 | 6,26 | 6571,41 | 14,56
C | Battleground Geist | 42017 | 6,9 | 6089,42 | 13,49
C | Ghoulraiser | 43013 | 7,22 | 5957,48 | 13,20
C | Traveler's Amulet | 44551 | 6,57 | 6780,97 | 15,02
C | Moonmist | 47206 | 8,89 | 5310,01 | 11,76
C | Vampiric Fury | 47338 | 8,86 | 5342,89 | 11,84
C | Haunted Fengraf | 47619 | 7,72 | 6168,26 | 13,66

This gives average rates of:

  | Avg rate
-- | --
M | 1,00
R | 2,07
U | 5,52
C | 13,36

So it's clear they don't appear at the same rate, but what exactly the rates are is difficult to estimate based off the small sample size of the only mythic in the set. At first glance it seems something like 1-2-6-12? Hard to be sure... But I think either those rates or 1-2-4-8 would better reflect the distribution than flat rates.

**Comment by taw** [comment]
Let's go with 1-2-6-12 if that's the empirical data.

**Comment by taw** [comment]
Updated to 1-2-6-12 . This should be all?

**Comment by fverdoja** [comment]
Thanks a lot, looks good to me
