### ISSUE TITLE
Rare + uncommon all in one color

### ISSUE THREAD

**Issue by tooomm** [taw/magic-sealed-data#4]
As just seen in M21 on dr4ft.info which uses your data:

![allred](https://user-images.githubusercontent.com/9874850/89186792-93d44d00-d59c-11ea-99d3-95bbe4f64dfa.png)

I assume that can't happen in real boosters? Was it just a rare edge case and bad luck?

Your data probably can't even fix that, just thought I let you know about this special occurrence.

**Comment by taw** [comment]
Each sheet is independent so color of the rare shouldn't affect colors of anything else (disregarding weird sets like DOM and WAR where there's cross-rarity guaranteed legend or planeswalker).

The way uncommon collation works ([example](https://www.lethe.xyz/mtg/collation/m21.html)), it's not really possible to have 3 uncommons of same color, but we don't simulate it at all.

In real boosters you could definitely get 1 red rare + 2 red uncommons. 1 red rare + 3 red uncommons is not supposed to happen.

([looking at old uncommon sheets, it looks like it used to be possible to get 3 of same color](http://forum.magiclibrarities.net/forum/viewtopic.php?f=6&t=9906), in some very old sets)

I don't think this is something we're going to simulate, as it would add a lot of complexity, but it's a possibility.

**Comment by tooomm** [comment]
Thanks for the comprehensive and informative reply and insights, taw!

**Comment by taw** [comment]
I'll just close this, since there's no real fix.
