### ISSUE TITLE
Shadows over Innistrad and Eldritch Moon common/uncommon DFC ratio is incorrect

### ISSUE THREAD

**Issue by awjackson** [taw/magic-sealed-data#5]
The weight of each common to each uncommon in the C/U DFC slot should be 5:2 in both sets, not 3:1. See https://www.lethe.xyz/mtg/collation/soi.html and https://www.lethe.xyz/mtg/collation/emn.html.

>Double-faced commons and uncommons appear in a long 120 card run (probably a sheet with one filler) with each common appearing ten times and each uncommon appearing four times.

>Double-faced commons and uncommons appear in a long 120 card run (probably a sheet with one filler) with each common appearing 15 times and each uncommon appearing six times.

**Comment by taw** [comment]
It's a generally reliable source, so I'll fix the ratios. Let me know if anything else is wrong.

**Comment by taw** [comment]
Fixed now, thanks.
