### ISSUE TITLE
Zendikar Rising and Modal Double Faced Cards (MDFC)

### ISSUE THREAD

**Issue by Senryoku** [taw/magic-sealed-data#6]
Afaik ZNR packs are guaranteed to contain exactly one MDFC but it's not reflected in the boosters variations/there's no MDFC sheets.
Since a similar case is correctly handled with WAR and its planeswalkers, I suppose it should be covered.

Thanks a lot for your work btw!

**Comment by taw** [comment]
Thanks, I'll take a look at it.

**Comment by taw** [comment]
Fixed now.

**Comment by Senryoku** [comment]
Sorry to re-use this closed issue (should I open a new one?), but the "-arena" version of ZNR doesn't implement this rule, is this intended?

**Comment by taw** [comment]
It's not implemented for Arena boosters yet.

**Comment by taw** [comment]
It's fixed now for Arena boosters as well.
