### ISSUE TITLE
Foil booster rate

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#7]
Hi,
I have notice the probability you have for boosters to get foils for most recent standard sets is 1:4 (25%).
However, unless I'm mistaken, I think this number is incorrect.

According to Wizards ([source](https://magic.wizards.com/en/articles/archive/making-magic/project-booster-fun-2019-07-20)):
> As part of the Project Booster Fun initiative, we decided to raise the frequency of foils. Previously, the foil drop rate (this is counting all foils of all rarities) was 1 in 67 cards (which results in a 22.5% chance of opening one in any one booster). The new drop rate is 1 in 45 cards (or a 33.4% chance of opening one in any one booster). This means the chance of getting a foil has increased from less than one in four boosters to one in three. As this was a change we could make within the existing system, we didn't bother waiting for Throne of Eldraine. You'll find this new foil drop rate starting with Core Set 2020. (Core Set 2020 also premieres a new token frame.)

This means that the probability should be 1:3 (33.4%) for sets from M20 forward (M20, ELD, THB, IKO, M21, ZNR, and KHM) and actually 9:40 (22.5%) for most sets before then.

**Comment by taw** [comment]
Yeah, I should definitely do this. I already fixed really old sets back when foils were at much lower drop rate (and kept rarity), no reason not to fix this too.

**Comment by taw** [comment]
@fverdoja  It should be fixed now. I think I got all the supplemental sets right as well, but if you could double check, that would be nice.

**Comment by fverdoja** [comment]
Looks good to me :) Thanks for this!
