### ISSUE TITLE
KHM dual snow lands in basic slot

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#8]
In the sheets for KHM, you have put a basic slot containing only the 10 basic lands. However in KHM the dual snow lands are also appearing in the basic land slot, as shown by them having rarity **L** in the lower corner of their frame ([ref](https://scryfall.com/search?q=set%3Akhm+t%3Aland+t%3Asnow+r%3Ac+unique%3Aart+-name%3Ashimmerdrift&unique=cards&as=grid&order=set)).

**Comment by taw** [comment]
Do we know their relative rates?

**Comment by fverdoja** [comment]
There are 2 variants for each snow basic which makes 10, and 10 nonbasic snow, I think a 1:1 rate seems reasonable, considering it was the same in M21, but no, I think we don't have official information on it.

**Comment by taw** [comment]
I put them there with 10+10 ratio. There's no reason to expect this ratio, previous sets have different ratios, so I'd prefer to get some official statement (or someone to just open a bunch of packs and give stats, even one or two box openings can likely say if it's like 1:1 or not).

**Comment by fverdoja** [comment]
I noticed you pushed the change, it looks good to me. The ratio you implemented is the one I was advocating for, so for me this can be considered closed if you want. Thanks. :)

**Comment by taw** [comment]
Your guess is reasonable. I would prefer either some official announcement, or at least someone to open a box and list its full contents (or just how many snow duals vs snow basics they got).

**Comment by Senryoku** [comment]
[This website](https://www.lethe.xyz/mtg/collation/khm.html) (which has thorough information on most sets) talks about a 5/12 ratio.

**Comment by fverdoja** [comment]
Interesting. 
It also says:
> The land run contains each variation of each basic snow land seven times and each common dual land five times.

So I guess the easiest would be to give each basic weight 7 and each dual weight 5.

**Comment by taw** [comment]
Ratio fixed to 7:5
