### ISSUE TITLE
Collector number suffixes appear inconsistent

### ISSUE THREAD

**Issue by nikklassen** [taw/magic-sealed-data#9]
Apologies if I am missing something here, but the letters at the end of collector numbers seem to be applied inconsistently. In Unstable the "Knight of the Kitchen Sink" card has multiple versions, each one suffixed with a-f. These letters match the collector number from Scryfall. But for MDFC from Zendikar Rising, they always have an "a" suffix, even though the collector number doesn't include this. Preferably MDFCs would not have a suffix.

**Comment by taw** [comment]
All cards (and card sides) have unique collector numbers, [that's it's all designed](https://mtg.wtf/).

I guess it seems somewhat pointless for this use case when card is 114a/114b, as booster always includes both sides.

**Comment by taw** [comment]
I'm not currently planning to add any additional ids other than mtgjson ids and mtg.wtf ids to the file, so closing this one.
